name: Email Action Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 21f3001219@ds.study.iitm.ac.in
        run: echo "Hello, world!"
